# Generated by Django 4.2.30 on 2026-04-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vcf_file', models.FileField(upload_to='vcf_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.CharField(max_length=50)),
                ('pos', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=500)),
                ('alt', models.CharField(max_length=500)),
                ('qual', models.FloatField(blank=True, null=True)),
                ('filter', models.CharField(blank=True, max_length=200)),
                ('sample_name', models.CharField(blank=True, max_length=200)),
                ('genotype', models.CharField(blank=True, max_length=100)),
                ('vaf', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('allelic_depth', models.CharField(blank=True, max_length=200)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('format_data', models.JSONField(blank=True, default=dict)),
                ('priority_score', models.FloatField(blank=True, null=True)),
                ('curation_status', models.CharField(default='pending', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='curation.vcfupload')),
            ],
            options={
                'ordering': ['-priority_score', 'chrom', 'pos'],
            },
        ),
    ]
