# Generated by Django 4.2.30 on 2026-04-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0004_alter_vcfupload_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='curation.vcfupload')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores_data', models.JSONField(default=dict, help_text='Complete scores CSV data')),
                ('clinical_report_html', models.TextField(blank=True, help_text='Generated clinical report HTML')),
                ('gene_roles_chart', models.TextField(blank=True, help_text='Base64 encoded gene roles chart')),
                ('mutation_origin_chart', models.TextField(blank=True, help_text='Base64 encoded mutation origin chart')),
                ('vaf_distribution_chart', models.TextField(blank=True, help_text='Base64 encoded VAF distribution chart')),
                ('analysis_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='curation.vcfupload')),
            ],
        ),
    ]
