# Generated by Django 4.2.30 on 2026-04-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0005_processinglog_analysisresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
