# Generated by Django 4.2.30 on 2026-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0006_remove_teammember_role_delete_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcfupload',
            name='vcf_content',
            field=models.TextField(blank=True, help_text='VCF file content stored in database', null=True),
        ),
        migrations.AlterField(
            model_name='vcfupload',
            name='vcf_file',
            field=models.FileField(blank=True, null=True, upload_to='vcf_uploads/'),
        ),
    ]
